# Generated by Django 2.1.7 on 2021-06-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20210623_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='year',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['year'], name='leave_leave_year_6f0133_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status'], name='leave_leave_status_34d281_idx'),
        ),
    ]
