# Generated by Django 2.1.7 on 2021-07-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20210624_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, unique=True)),
                ('value', models.CharField(max_length=366)),
            ],
        ),
    ]
