# Generated by Django 2.1.7 on 2021-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leavemask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemask',
            name='value',
            field=models.TextField(max_length=366),
        ),
    ]
