# Generated by Django 2.1.7 on 2021-07-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20210705_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemask',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='leavemask',
            name='value',
            field=models.TextField(max_length=732),
        ),
    ]
