# Generated by Django 2.1.7 on 2021-07-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20210712_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemask',
            name='summary',
            field=models.TextField(),
        ),
    ]
