# Generated by Django 2.1.7 on 2022-04-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_leavemask_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('country_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
