# Generated by Django 2.1.7 on 2022-04-29 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0010_leavemask_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_pass', models.CharField(blank=True, choices=[('SGC', 'SG Citizen'), ('PRS', 'Permanent Resident'), ('EPS', 'Employment Pass'), ('SPS', 'S Pass')], default=None, help_text="For Singaporean Only, otherwise it'll be ignored", max_length=3, null=True)),
                ('join_date', models.DateField()),
                ('children', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('children_birth_year', models.CharField(blank=True, default=None, help_text='Year(s) separated by semicolon (;)', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=20)),
                ('typ', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('country_code', leave.models.LowerCaseField(max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.Country'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
