# Generated by Django 2.1.7 on 2022-04-13 01:11

from django.db import migrations
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=leave.models.LowerCaseField(max_length=10, unique=True),
        ),
    ]
