# Generated by Django 2.1.7 on 2022-04-13 08:47

from django.db import migrations
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_auto_20220413_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=leave.models.LowerCaseField(max_length=20, unique=True),
        ),
    ]
