# Generated by Django 2.1.7 on 2022-04-20 22:25

from django.db import migrations
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_auto_20220413_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=leave.models.LowerCaseField(max_length=2, unique=True),
        ),
    ]
