# Generated by Django 2.1.7 on 2022-04-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_auto_20220421_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('year', models.CharField(default=None, max_length=20)),
                ('typ', models.CharField(max_length=255)),
                ('days', models.IntegerField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
