# Generated by Django 2.1.7 on 2022-08-26 06:01

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('country_code', account.models.LowerCaseField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='LeaveRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_pass', models.CharField(blank=True, choices=[('SGC', 'SG Citizen'), ('PRS', 'Permanent Resident'), ('EPS', 'Employment Pass'), ('SPS', 'S Pass')], default=None, help_text="For Singapore employees only, otherwise it'll be ignored", max_length=3, null=True)),
                ('leave_type', models.CharField(choices=[('PR', 'Personal'), ('CO', 'Compassionate'), ('CC', 'Childcare'), ('MD', 'Medical'), ('WH', 'Work From Home')], default='PR', max_length=2)),
                ('year', models.CharField(blank=True, help_text="Year when this rule will be applied,\n\n                               When empty it'll be applied forever.", max_length=4, null=True)),
                ('days', models.IntegerField(default=0, help_text='Leave limit in days/year per child')),
                ('children_max_age', models.IntegerField(default=0, help_text='Maximum age of eligible child <br>                                            Only applied to Childcare Leave')),
                ('max_days', models.IntegerField(default=0, help_text='Maximum leave days/year <br>                                           (leave will be counted as days * number of eligible child) <br>                                           Only applied to Childcare Leave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Country')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mentorship',
            options={'verbose_name': 'Account Profile', 'verbose_name_plural': 'Account Profiles'},
        ),
        migrations.AddField(
            model_name='mentorship',
            name='children',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='children_birth_year',
            field=models.CharField(blank=True, default=None, help_text='Year(s) separated by semicolon (;)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('BO', 'Backoffice'), ('SA', 'System Admin'), ('OP', 'Operations'), ('DA', 'Data'), ('DV', 'Developer'), ('RS', 'Researcher')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='join_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='teammate',
            field=models.ManyToManyField(blank=True, related_name='teammates', related_query_name='teammates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='work_pass',
            field=models.CharField(blank=True, choices=[('SGC', 'SG Citizen'), ('PRS', 'Permanent Resident'), ('EPS', 'Employment Pass'), ('SPS', 'S Pass')], default=None, help_text="For Singapore employees only, otherwise it'll be ignored", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='employment_status',
            field=models.CharField(choices=[('INTERN', 'Intern'), ('EMPLOYEE', 'Employee'), ('PEMPLOYEE', 'Past Employee')], default='EMPLOYEE', max_length=10),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Country'),
        ),
    ]
