# Generated by Django 2.1.7 on 2021-12-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr_app', '0004_auto_20211220_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
