# Generated by Django 2.1.7 on 2021-03-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_compliance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
