stages:
  - coding-style
  - build

python-coding-style-check:
  image: python:3.6-slim
  stage: coding-style
  tags:
    - docker
  script:
    - pip install -U pip
    - pip install flake8
    - flake8 .

build-docker-image:
  stage: build
  tags:
    - image-build
  script:
    - tag=$(git describe --tags) && echo $tag
    - imagetag=docker.dtl:5000/ado/docker-images/eardrum/r48:$tag && echo $imagetag
    - docker build -t $imagetag .
    - docker push $imagetag
  when: manual
