# Generated by Django 2.0 on 2021-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
