# Generated by Django 2.1.7 on 2019-06-28 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('extra', models.CharField(help_text='Weights of question in the format of \
                                           "question_id:weight;question_id:weight;..."', max_length=255)),
                ('ordering', models.CharField(blank=True, default='',
                                              help_text='Ordering of questions will be listed in format of \
                                                         "question1_id,question2_id,question3_id,.."',
                                              max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='{}')),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('quarter_and_year', models.CharField(blank=True, default='2,2019', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Bucket')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='user_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='reviewee_requests', related_query_name='reviewee_request',
                                               to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='reviewer_requests', related_query_name='reviewer_request',
                                               to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bucket',
            name='questions',
            field=models.ManyToManyField(to='review.Question'),
        ),
    ]
