# Generated by Django 2.1.7 on 2019-07-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='issuer',
        ),
        migrations.AddField(
            model_name='question',
            name='typ',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='quarter_and_year',
            field=models.CharField(blank=True, default='3,2019', max_length=10),
        ),
    ]
