# Generated by Django 2.1.7 on 2019-07-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20190711_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
