# Generated by Django 2.1.7 on 2021-01-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190711_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='quarter_and_year',
            field=models.CharField(blank=True, default='q,yyyy', max_length=10),
        ),
    ]
