# Generated by Django 2.1.7 on 2022-01-07 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('review', '0004_auto_20210127_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Bucket')),
                ('mentorship', models.ManyToManyField(to='account.Mentorship')),
            ],
        ),
    ]
