# Generated by Django 2.1.7 on 2022-01-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_templaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templaterequest',
            name='mentorship',
            field=models.ManyToManyField(related_name='template_requests', to='account.Mentorship'),
        ),
    ]
